name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]

      - name: Build
        run: pnpm docs:build

      - name: Config
        run: echo 'blog.niuiic.com' > docs/.vitepress/dist/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
